// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VigenereCipherWeb.Data;

#nullable disable

namespace VigenereCipherWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119170958_InitialCreatePostgres")]
    partial class InitialCreatePostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VigenereCipherWeb.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auth0UserId = "auth0|demo1",
                            Email = "demo@example.com",
                            Username = "demo_user"
                        },
                        new
                        {
                            Id = 2,
                            Auth0UserId = "auth0|demo2",
                            Email = "test@example.com",
                            Username = "test_user"
                        });
                });

            modelBuilder.Entity("VigenereCipherWeb.Data.CipherJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CipherMethodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CipherMethodId");

                    b.ToTable("CipherJobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            CipherMethodId = 1,
                            CreatedAt = new DateTime(2025, 11, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            InputText = "HELLO",
                            Key = "KEY",
                            Operation = "encrypt",
                            ResultText = "RIJVS"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 1,
                            CipherMethodId = 1,
                            CreatedAt = new DateTime(2025, 11, 16, 14, 20, 0, 0, DateTimeKind.Utc),
                            InputText = "WORLD",
                            Key = "KEY",
                            Operation = "encrypt",
                            ResultText = "CPSME"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 2,
                            CipherMethodId = 2,
                            CreatedAt = new DateTime(2025, 11, 17, 9, 15, 0, 0, DateTimeKind.Utc),
                            InputText = "SECRET",
                            Key = "ABC",
                            Operation = "decrypt",
                            ResultText = "TFDSFU"
                        });
                });

            modelBuilder.Entity("VigenereCipherWeb.Data.CipherMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CipherMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Класичний шифр Віженера з буквеним ключем",
                            Name = "Vigenere"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Шифр Цезаря зі зсувом алфавіту",
                            Name = "Caesar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Біграмний шифр Плейфера",
                            Name = "Playfair"
                        });
                });

            modelBuilder.Entity("VigenereCipherWeb.Data.CipherJob", b =>
                {
                    b.HasOne("VigenereCipherWeb.Data.AppUser", "AppUser")
                        .WithMany("CipherJobs")
                        .HasForeignKey("AppUserId");

                    b.HasOne("VigenereCipherWeb.Data.CipherMethod", "CipherMethod")
                        .WithMany("CipherJobs")
                        .HasForeignKey("CipherMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("CipherMethod");
                });

            modelBuilder.Entity("VigenereCipherWeb.Data.AppUser", b =>
                {
                    b.Navigation("CipherJobs");
                });

            modelBuilder.Entity("VigenereCipherWeb.Data.CipherMethod", b =>
                {
                    b.Navigation("CipherJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
