version: '3.8'



services:


  postgres_db:

    image: postgres:15        

    container_name: vigenere-postgres-db 
    environment:

      POSTGRES_PASSWORD: password

      POSTGRES_USER: postgres

      POSTGRES_DB: VigenereCipherDb 
    ports:


      - "5432:5432"

    volumes:


      - postgres_data:/var/lib/postgresql/data



volumes:

  postgres_data:
